apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
  namespace: alert-service
  labels:
    app: receiver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver-service
  template:
    metadata:
      labels:
        app: receiver-service
    spec:
      containers:
      - name: receiver
        image: claretyoung/receiver
        ports:
        - containerPort: 8071
        env:
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: secrets
              key: pg-host
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: pg-username
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: pg-password
        - name: RMQ_HOST
          valueFrom:
            secretKeyRef:
              name: secrets
              key: rmq-host
        - name: RMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: rmq-username
        - name: RMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: rmq-password
