apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiverdb
  namespace: alert-service
  labels:
    app: receiver-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver-db
  template:
    metadata:
      labels:
        app: receiver-db
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: postgres-password

