apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
  namespace: alert-service
  labels:
    app: sender-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender-service
  template:
    metadata:
      labels:
        app: sender-service
    spec:
      containers:
      - name: sender
        image: claretyoung/sender
        ports:
        - containerPort: 8070
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: secrets
              key: mysql-host
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: mysql-password
        - name: RMQ_HOST
          valueFrom:
            secretKeyRef:
              name: secrets
              key: rmq-host
        - name: RMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: rmq-username
        - name: RMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: rmq-password
        - name: RECEIVER_HOST
          valueFrom:
            secretKeyRef:
              name: secrets
              key: receiver-host