apiVersion: v1
kind: Service
metadata:
  name: senderservice
  namespace: alert-service
  labels:
    app: sender-service
spec:
  selector:
    app: sender-service
  ports:
  - port: 8070
    targetPort: 8070
