version: '3.3'

services:
  sender:
    ports:
      - 8071:8071
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PG_HOST=${PG_HOST}
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASSWORD=${PG_PASSWORD}
      - RMQ_HOST=${RMQ_HOST}
      - RMQ_USERNAME=${RMQ_USERNAME}
      - RMQ_PASSWORD=${RMQ_PASSWORD}
