apiVersion: v1
kind: Service
metadata:
  name: rmqservice
  namespace: alert-service
  labels:
    app: rmq-message
spec:
  selector:
    app: rmq-message
  ports:
  - port: 5672
    targetPort: 5672
